config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts do
    get :search, on: :collection
  end
  resources :comments, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, :author, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch::Model
  extend FriendlyId

  # Validações
  validates :title, :author, :body, presence: true

  # Relações
  has_many :comments, dependent: :destroy

  # FriendlyId para slugs
  friendly_id :title, use: :slugged

  # Configuração do pg_search para busca de um título do post ou o conteúdo do mesmo
  pg_search_scope :search,
    against: %i[title author body],
    associated_against: {
      comments: %i[body]
    },
    using: {
      tsearch: { prefix: true }
    }

  # Método para determinar quando regenerar o slug
  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create!(comments_params)
    redirect_to comment.post, notice: "O seu comentário foi enviado!"
  end

  private

  def comments_params
    params.require(:comment).permit(:post_id, :author, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments
    @comment = Comment.new
  end

  # GET /posts/search
  def search
    @posts = Post.search(params[:q]) || []
    render :index
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post foi criado com sucesso." }
        format.json { render :show, status: :created, location: @post }
      else
        flash.now[:alert] = @post.errors.full_messages.to_sentence
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    if @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post foi removido com sucesso." }
        format.json { head :no_content }
      end
    else
      flash[:alert] = "Erro ao tentar apagar o post."
      redirect_to posts_url
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "O post que você está procurando não foi encontrado."
    redirect_to posts_path
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :author, :body)
  end

  def search_params
    params.permit(:q)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# <link rel="manifest" href="/manifest.json"> %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <header class="bg-primary text-white text-center mb-4 p-4">
      <%= link_to root_path, class: 'text-white text-decoration-none' do %>
        <h1 class="display-4">Blog de TI</h1>
      <% end %>
      <p class="lead">Olá, aqui você encontrará artigos sobre programação, tecnologia e carreira.</p>
    </header>
    
    <main class="flex-grow-1">
      <div class="container">
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>

        <div class="row">
          <div class="col-4 offset-8">
            <div class="search">
              <%= form_with url: search_posts_path, method: :get, local: true, class: 'd-inline-flex' do |form| %>
                <div class="form-group mx-3 mb-3">
                  <%= form.search_field :q, class: 'form-control', required: true, placeholder: 'Busca', value: params[:q] %>
                </div>
                <%= form.submit 'Buscar', class: 'btn btn-primary mb-3', data: { disable_with: 'Buscando...' } %>
              <% end %>
            </div>
          </div>
        </div>

        <%= yield %>
      </div>
    </main>

    <footer class="bg-primary text-white text-center mt-5 p-4">
      © Copyright Thiago Nascimento <%= Date.current.year %>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows:  5 %>
  </div>

  <%= form.submit class: 'btn btn-primary mt-3', data: {disable_with:'Enviando...'} %>
<% end %>

app/views/posts/_post.html.erb
<div class="card bg-light mb-3">
  <div class="card-body">
    <h4><%= link_to post.title, post, class: 'text-decoration-none' %></h4>
    <div class="text-muted mb-2">
      <em>Por <%= post.author %> (<%= l(post.created_at, format: :short) %>)</em>
    </div>

    <p><%= post.body.truncate(200) %></p>

    <p class="text-muted"><% pluralize(post.comments.count, 'Comentário') %> </p>

  <div class= 'btn btn-primary'>    
    <%= link_to "Ler Artigo" , post, class: 'text-white text-decoration-none' %>
    <i class="bi bi-search"></i>
  </div>

  <div class= 'btn btn btn-secondary'>    
    <%= link_to "Editar" , edit_post_path(post), class: 'text-white text-decoration-none' %>
    <i class="bi bi-pen"></i>
  </div>

  <div class= 'btn btn-danger'>    
    <%= link_to "Apagar" , post, method: :delete, class: 'text-white text-decoration-none', data: {confirm:'Você tem certeza?'} %>
    <i class="bi bi-trash"></i>
  </div>


  </div>
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editar post" %>

<h1>Editar Post</h1>

<%= render "form", post: @post %>

<br>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<%= render(post)%>
<% end %>

<hr>

<div class="text-right">
  <%= link_to "Novo post", new_post_path, class: 'btn btn-success'%>
</div>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

app/views/posts/search.html.erb
<div class="text-muted">
  <% if @posts.any? %>
  <h2><%= pluralize(@posts.count, 'resultado') %> encontrados</h2>
  <% else %>
    Nenhum resultado encontrado
  <% end %>
</div>

<% if @posts.present? %>
  <% @posts.each do |post| %>
    <h2><%= pluralize(@posts.count, 'resultado') %> encontrados</h2>

    <%= render post %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<div class="shadow p-3 mb-5 rounded">
  <div class="text-center mb-5">
    <h1><%= @post.title %></h1>
    <p class="text-muted">
      <strong>Por <%= @post.author %></strong><br>
      <%= l @post.created_at, format: :long %>
    </p>
  </div>

  <div class="px-5">
    <%= @post.body.gsub("\n","</br>").html_safe %>
  </div>
</div>

<div class="m-5">
  <div class="text-center">
    <h4>
      <%= pluralize(@post.comments.count, 'Comentário') %>
      <% if @post.comments.none?%>
        <span class="badge text-bg-success">Seja o primeiro a comentar!</span>
      <% end %>
    </h4>
  </div>

  <div class="shadow-sm m-3 p-3 bg-light rounde">
    <%= form_with model: @comment, local: true do |form| %>
      <%= form.hidden_field :post_id, value: @post.id %>
      <div class="form-group">
        <%= form.label :author %>
        <%= form.text_field :author, class: 'form-control mb-3', required: true %>
      </div>

      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows:  2, required: true %>
      </div>

      <%= form.submit 'Enviar', class: 'btn btn-primary mt-3', data: {disable_with:'Enviando...'} %>

    <% end %>
  </div>
 
    <% @comments.each do |comment| %>
      <div class="shadow-sm m-3 p-3 bg-light rounded border">
        <div class="d-flex justify-content-between">
          <div>
            <%= comment.author %>
          </div>
          <div class="text-right">
            <em title="<%= l comment.created_at, format: :long%>" data-bs-toggle="tooltip" data-bs-placement="top">
              <%= time_ago_in_words comment.created_at %> atrás
            </em>
          </div>
        </div>

        <hr>

        <%= sanitize(comment.body.gsub("\n","</br>").html_safe)%>
      </div>

    <% end %>
</div>